apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: health-platform
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30080
  type: NodePort
